//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLFA.Clases {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoLFA.Clases.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a import time
        ///
        ///def get_stack(input_string):
        ///    # Se invierte la cadena para simular la pila
        ///    return list(reversed(input_string))
        ///
        ///def error():
        ///    print(&quot;\nError: La cadena no es válida&quot;)
        ///
        ///def valido(token):
        ///    print(&quot;\n&quot; + token + &quot; » &quot; + str(get_token_number(token)))
        ///    return &quot;&quot;
        ///
        ///def get_token_number(text):
        ///    first_character_from_text = text[0]
        ///    last_character_from_text = text[-1]
        ///
        ///    character_token_first = {
        ///# Define aquí los tokens correspondientes
        ///}
        ///
        ///character_token_las [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Threading;
        ///using System.Windows.Forms;
        ///
        ///namespace Scanner
        ///{
        ///    class Program
        ///    {
        ///        static void Main(string[] args)
        ///        {
        ///            Stack&lt;char&gt; Input = new Stack&lt;char&gt;();
        ///
        ///            Inicio:
        ///
        ///            Console.Write(&quot;\nEscriba la cadena para analizar: &quot;);
        ///            Input = getStack(Console.ReadLine());
        ///
        ///            Console.Write(&quot;\nAnalizando&quot;);
        ///            Thread.Sleep(300);
        ///            Console.Write(&quot;.&quot;);
        ///   [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
    }
}
